/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WebsiteIndexRouteImport } from './routes/website/index'
import { Route as WebsiteAboutRouteImport } from './routes/website/about'
import { Route as WebsiteCatalogRouteImport } from './routes/website/catalog'
import { Route as WebsiteContactRouteImport } from './routes/website/contact'
import { Route as WebsiteTradeRouteImport } from './routes/website/trade'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCashiersRouteImport } from './routes/_authenticated/admin.cashiers'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminPosRouteImport } from './routes/_authenticated/admin.pos'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as WebsiteProductProductIdRouteImport } from './routes/website/product.$productId'
import { Route as AuthenticatedAdminInvoicesIndexRouteImport } from './routes/_authenticated/admin.invoices.index'
import { Route as AuthenticatedAdminInvoicesInvoiceIdRouteImport } from './routes/_authenticated/admin.invoices.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/website/',
  path: '/website/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAboutRoute = WebsiteAboutRouteImport.update({
  id: '/website/about',
  path: '/website/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteCatalogRoute = WebsiteCatalogRouteImport.update({
  id: '/website/catalog',
  path: '/website/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteContactRoute = WebsiteContactRouteImport.update({
  id: '/website/contact',
  path: '/website/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteTradeRoute = WebsiteTradeRouteImport.update({
  id: '/website/trade',
  path: '/website/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCashiersRoute =
  AuthenticatedAdminCashiersRouteImport.update({
    id: '/admin/cashiers',
    path: '/admin/cashiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/admin/customers',
    path: '/admin/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/admin/inventory',
    path: '/admin/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPosRoute = AuthenticatedAdminPosRouteImport.update({
  id: '/admin/pos',
  path: '/admin/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WebsiteProductProductIdRoute = WebsiteProductProductIdRouteImport.update({
  id: '/website/product/$productId',
  path: '/website/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminInvoicesIndexRoute =
  AuthenticatedAdminInvoicesIndexRouteImport.update({
    id: '/admin/invoices/',
    path: '/admin/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesInvoiceIdRoute =
  AuthenticatedAdminInvoicesInvoiceIdRouteImport.update({
    id: '/admin/invoices/$invoiceId',
    path: '/admin/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/catalog': typeof WebsiteCatalogRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/trade': typeof WebsiteTradeRoute
  '/website/': typeof WebsiteIndexRoute
  '/admin/cashiers': typeof AuthenticatedAdminCashiersRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/website/product/$productId': typeof WebsiteProductProductIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/catalog': typeof WebsiteCatalogRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/trade': typeof WebsiteTradeRoute
  '/website': typeof WebsiteIndexRoute
  '/admin/cashiers': typeof AuthenticatedAdminCashiersRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/website/product/$productId': typeof WebsiteProductProductIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/website/about': typeof WebsiteAboutRoute
  '/website/catalog': typeof WebsiteCatalogRoute
  '/website/contact': typeof WebsiteContactRoute
  '/website/trade': typeof WebsiteTradeRoute
  '/website/': typeof WebsiteIndexRoute
  '/_authenticated/admin/cashiers': typeof AuthenticatedAdminCashiersRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/pos': typeof AuthenticatedAdminPosRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/website/product/$productId': typeof WebsiteProductProductIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/_authenticated/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/website/about'
    | '/website/catalog'
    | '/website/contact'
    | '/website/trade'
    | '/website/'
    | '/admin/cashiers'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/pos'
    | '/admin/reports'
    | '/website/product/$productId'
    | '/admin/'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/website/about'
    | '/website/catalog'
    | '/website/contact'
    | '/website/trade'
    | '/website'
    | '/admin/cashiers'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/pos'
    | '/admin/reports'
    | '/website/product/$productId'
    | '/admin'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/website/about'
    | '/website/catalog'
    | '/website/contact'
    | '/website/trade'
    | '/website/'
    | '/_authenticated/admin/cashiers'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/pos'
    | '/_authenticated/admin/reports'
    | '/website/product/$productId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/invoices/$invoiceId'
    | '/_authenticated/admin/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  WebsiteAboutRoute: typeof WebsiteAboutRoute
  WebsiteCatalogRoute: typeof WebsiteCatalogRoute
  WebsiteContactRoute: typeof WebsiteContactRoute
  WebsiteTradeRoute: typeof WebsiteTradeRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
  WebsiteProductProductIdRoute: typeof WebsiteProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/': {
      id: '/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/about': {
      id: '/website/about'
      path: '/website/about'
      fullPath: '/website/about'
      preLoaderRoute: typeof WebsiteAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/catalog': {
      id: '/website/catalog'
      path: '/website/catalog'
      fullPath: '/website/catalog'
      preLoaderRoute: typeof WebsiteCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/contact': {
      id: '/website/contact'
      path: '/website/contact'
      fullPath: '/website/contact'
      preLoaderRoute: typeof WebsiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website/trade': {
      id: '/website/trade'
      path: '/website/trade'
      fullPath: '/website/trade'
      preLoaderRoute: typeof WebsiteTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cashiers': {
      id: '/_authenticated/admin/cashiers'
      path: '/admin/cashiers'
      fullPath: '/admin/cashiers'
      preLoaderRoute: typeof AuthenticatedAdminCashiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pos': {
      id: '/_authenticated/admin/pos'
      path: '/admin/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AuthenticatedAdminPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/website/product/$productId': {
      id: '/website/product/$productId'
      path: '/website/product/$productId'
      fullPath: '/website/product/$productId'
      preLoaderRoute: typeof WebsiteProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/invoices/': {
      id: '/_authenticated/admin/invoices/'
      path: '/admin/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/invoices/$invoiceId': {
      id: '/_authenticated/admin/invoices/$invoiceId'
      path: '/admin/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCashiersRoute: typeof AuthenticatedAdminCashiersRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminPosRoute: typeof AuthenticatedAdminPosRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminInvoicesInvoiceIdRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  AuthenticatedAdminInvoicesIndexRoute: typeof AuthenticatedAdminInvoicesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCashiersRoute: AuthenticatedAdminCashiersRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminPosRoute: AuthenticatedAdminPosRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminInvoicesInvoiceIdRoute:
    AuthenticatedAdminInvoicesInvoiceIdRoute,
  AuthenticatedAdminInvoicesIndexRoute: AuthenticatedAdminInvoicesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  WebsiteAboutRoute: WebsiteAboutRoute,
  WebsiteCatalogRoute: WebsiteCatalogRoute,
  WebsiteContactRoute: WebsiteContactRoute,
  WebsiteTradeRoute: WebsiteTradeRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
  WebsiteProductProductIdRoute: WebsiteProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
